"""empty message

Revision ID: 487ef2827fc8
Revises: b58ce9b5d070
Create Date: 2025-07-16 19:26:20.929936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487ef2827fc8'
down_revision = 'b58ce9b5d070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('color_de_pelo', sa.Integer(), nullable=False),
    sa.Column('altura', sa.String(), nullable=False),
    sa.Column('color_de_ojos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('clima', sa.String(), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.Column('terreno', sa.String(), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clima', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('diametro', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('terreno', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('población', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planets_pkey')
    )
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
