"""empty message

Revision ID: b21212067b86
Revises: 487ef2827fc8
Create Date: 2025-07-18 14:34:22.446842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21212067b86'
down_revision = '487ef2827fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fecha_de_subscripcion', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fecha_de_subscripcion')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
