"""empty message

Revision ID: b58ce9b5d070
Revises: a5cffa318ac2
Create Date: 2025-07-16 19:06:06.893619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58ce9b5d070'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('clima', sa.String(), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.Column('terreno', sa.String(), nullable=False),
    sa.Column('población', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
