"""empty message

Revision ID: cdb21a4597f7
Revises: 50a00f9124f8
Create Date: 2025-07-20 17:51:22.351281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb21a4597f7'
down_revision = '50a00f9124f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_character_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_character_character_id_fkey', 'planet', ['character_id'], ['id'])

    # ### end Alembic commands ###
